topics:
  schweizer_wirtschaft:
    include: ["Schweiz", "Wirtschaft", "Unternehmen", "Finanz", "Bank", "Versicherung"]
    confidence_threshold: 0.70
    
  fintech:
    include: ["Fintech", "Krypto", "Zahlung", "Digitale Bank", "Neobank"]
    confidence_threshold: 0.75

  bonitaet_b2b_ch:
    description: >
      Bonität & Unternehmens-Kreditrisiko in der Schweiz (B2B).
      Fokus: Firmenratings/-scores, B2B-Zahlungsmoral, Konkurs-/Betreibungsstatistik,
      Regulatorik (Basel III Finalisierung CH, FINMA), Daten/Compliance (nDSG).
      Keine Inkasso-Operatives, keine Privatkredite.
    
    # Current system compatibility - flattened keywords for AI context
    include: [
      "Bonität", "Bonitätsprüfung", "Bonitätsauskunft", "Firmenrating", "Ratingagentur", "Score", "Scoring", "Kreditscoring",
      "Zahlungsmoral", "Zahlungsverzug", "Zahlungsfristen", "Debitoren", "Forderungsmanagement", 
      "Konkurs", "Insolvenz", "Betreibungen", "SchKG", "Firmenpleite",
      "Basel III", "Basel-III-Finalisierung", "Standardansatz", "RWA", "Swiss finish", "FINMA",
      "Datenschutzgesetz", "nDSG", "DSGVO", "Datenweitergabe", "Datenqualität",
      "Trade Credit Insurance", "Warenkreditversicherung", "Kreditversicherung",
      "KMU Finanzierung", "Unternehmenskredit", "Firmenkredit",
      "BFS", "Bundesamt für Statistik", "SNB", "SwissBankers", "SBVg", "Creditreform", "CrediWeb",
      "Basel Committee", "BCBS", "Allianz Trade", "Coface", "Atradius", "Intrum", "Dun & Bradstreet"
    ]
    confidence_threshold: 0.70
    
    # Extended configuration for future enhancements
    languages: ["de", "fr", "it", "en"]
    region_hint: ["CH"]
    
    include_keywords:
      - ["Bonität", "Bonitätsprüfung", "Bonitätsauskunft", "Firmenrating", "Ratingagentur", "Score", "Scoring", "Kreditscoring"]
      - ["Zahlungsmoral", "Zahlungsverzug", "Zahlungsfristen", "Debitoren", "Forderungsmanagement"]
      - ["Konkurs", "Insolvenz", "Betreibungen", "SchKG", "Firmenpleite"]
      - ["Basel III", "Basel-III-Finalisierung", "Standardansatz", "RWA", "Swiss finish", "FINMA"]
      - ["Datenschutzgesetz", "nDSG", "DSGVO", "Datenweitergabe", "Datenqualität"]
      - ["Trade Credit Insurance", "Warenkreditversicherung", "Kreditversicherung"]
      - ["KMU Finanzierung", "Unternehmenskredit", "Firmenkredit"]

    named_entities_anchor:
      - ["BFS", "Bundesamt für Statistik"]
      - ["FINMA"]
      - ["SNB"]
      - ["SwissBankers", "SBVg"]
      - ["Creditreform", "CrediWeb"]
      - ["Basel Committee", "BCBS"]
      - ["Allianz Trade", "Coface", "Atradius"]
      - ["Intrum", "Dun & Bradstreet"]

    exclude_keywords:
      - ["Inkasso", "Forderungseinzug", "Betreibung gegen Privatperson", "Schuldenberatung"]
      - ["Privatkredit", "Kreditkarte", "Hypothekenzins für Privat", "Konsumkredit"]
      - ["Rabattaktion", "Bonusprogramm", "Filialöffnung", "Produktwerbung"]

    sources_allowlist:
      - "nzz.ch"
      - "srf.ch"
      - "handelszeitung.ch"
      - "finews.ch"
      - "fuw.ch"
      - "cash.ch"
      - "admin.ch"
      - "seco.admin.ch"
      - "snb.ch"
      - "bfs.admin.ch"
      - "intrum.ch"
      - "dnb.com"

    google_news_queries:
      - 'bonität ODER bonitätsprüfung ODER firmenrating site:ch  | hl=de-CH&gl=CH&ceid=CH:de'
      - 'zahlungsmoral ODER zahlungsverzug site:ch           | hl=de-CH&gl=CH&ceid=CH:de'
      - 'konkurs ODER betreibungen ODER schkg site:admin.ch  | hl=de-CH&gl=CH&ceid=CH:de'
      - '"Basel III" ODER "Swiss finish" site:ch             | hl=de-CH&gl=CH&ceid=CH:de'
      - 'datenschutzgesetz ODER nDSG site:admin.ch           | hl=de-CH&gl=CH&ceid=CH:de'
      - 'kreditversicherung ODER "trade credit insurance" site:ch | hl=de-CH&gl=CH&ceid=CH:de'

    thresholds:
      title_url_gate_min_confidence: 0.70
      keep_if_entity_anchor_hit: true
      drop_if_exclude_keyword: true
